name: Build FYP-Software application

on:
  push:
    tags:
      - "v*"
jobs:
  build-with-cli2:
    container:
      image: ghcr.io/armmbed/mbed-os-env:master-latest

    runs-on: ubuntu-latest

    env:
      target: STM32F407VE_BLACK

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.BORG_TOKEN }}
          submodules: recursive
      -
        name: deploy-fyp-application
        run: |
          set -e
          mbed deploy
      -
        name: Updating to Mbed6
        run: |
          sed -i -e 's/wait_ms(/ThisThread::sleep_for(/g' WIZnetInterface/arch/ext/W5500.cpp
          sed -i -e 's/wait(/ThisThread::sleep_for(/g' WIZnetInterface/arch/ext/W5500.cpp
      -
        name: build-fyp-application
        run: |
            mbed-tools configure -t GCC_ARM -m ${{ env.target }}
            mbed-tools compile -t GCC_ARM -m ${{ env.target }}
      -
        name: create_release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
            repo_token: "${{ secrets.GITHUB_TOKEN }}"
            prerelease: false
            title: "Releases"
            files: |
                cmake_build/${{ env.target }}/develop/GCC_ARM/fyp18-03.bin